### ISSUE TITLE
Tmux completion from bash-it project

### ISSUE THREAD

**Issue by imomaliev** [przepompownia/tmux-bash-completion#2]
Hi, I recently found out that tmux's default completion (version 2.1) doesn't complete files, so i searched internet and found  more complete script, with file completion support in [bash-it](https://github.com/Bash-it/bash-it/) project
https://github.com/Bash-it/bash-it/blob/master/completion/available/tmux.completion.bash. So I
commented on [commit](https://github.com/tmux/tmux/commit/a33bb3e876895ef40ee90e5f89c76184e65c7f10) and was [told](https://github.com/tmux/tmux/commit/a33bb3e876895ef40ee90e5f89c76184e65c7f10#commitcomment-17657012) to ask you about updating it, because you are current maintainer of completion script.

**Comment by przepompownia** [comment]
It seems to be good idea to replace hte link to my simple script with that from _bash-it_. The only proposition from my side is replace constant command list `_tmux_cmds` with dynamic `"$(tmux list-commands | cut -d' ' -f1)"` or something more accurate.

**Comment by imomaliev** [comment]
> The only proposition from my side is to replace constant command list _tmux_cmds with dynamic "$(tmux list-commands | cut -d' ' -f1)" or something more accurate.

It is done this way so completion will work even when tmux server is down

> t seems to be good idea to replace the link to my simple script with that from bash-it

So should i create a pull request that will change that link?

**Comment by przepompownia** [comment]
Since version 2.1 we do not need working tmux server to do that. 

https://github.com/przepompownia/tmux-bash-completion/commit/76f8d9d02cd78cca80a4214a39ea3920bb1c689f

Independently of the above, feel free to creating PR.

**Comment by imomaliev** [comment]
Tmux now links to my repo, I think we can close this issue.
